apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.database.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc }}
  POSTGRES_HOST: {{ .Values.database.host | b64enc }}
  POSTGRES_PORT: {{ .Values.database.port | b64enc }}
